name: Compile and Publish Resume

on:
  schedule:
    - cron: 0 4 * * * # every day at 4:00 UTC
  release:
    types: published
  push:
    paths:
      - .github/workflows/build-deploy.yml

env:
  resume-file: latest.pdf
  artifact-id: resume

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - run: pacman -Sy --noconfirm chromium diffutils ghostscript nodejs
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: true

      - name: Verify manual hyphenation
        id: hyphenation-check
        run: |
          OUTPUT=expected.png HYPHENATE=yes pnpm build && mv dist/expected.png .
          OUTPUT=actual.png   HYPHENATE=no  pnpm build && mv dist/actual.png .
          diff --brief expected.png actual.png

      - name: Compile and compress PDF
        run: |
          OUTPUT=raw.pdf HYPHENATE=no TWOPASS=yes pnpm build
          IN=raw.pdf OUT=${{ env.resume-file }}   pnpm ghost

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ env.artifact-id }}
          path: dist/${{ env.resume-file }}

      - if: steps.hyphenation-check.outcome == 'failure'
        name: Upload hyphenation error report
        uses: actions/upload-artifact@v7
        with:
          name: hyphenation-error-report
          path: |
            expected.png
            actual.png

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages

    steps:
      - name: Download resume artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.artifact-id }}

      - name: Create minimalistic index.html
        run: |
          cat << EOF > index.html
          <meta http-equiv="refresh" content="0; URL=./${{ env.resume-file }}">
          EOF

      - uses: actions/upload-pages-artifact@v4
        with:
          path: .
      - uses: actions/deploy-pages@v5
